import { tintedPalette } from './palette';
import type { BuiltinTheme, ThemeDefinition } from './schema';

function landscape(
  id: string,
  name: string,
  description: string,
  category: ThemeDefinition['category'],
  decoration: ThemeDefinition['decoration'],
  hue: string,
  lightAccent: string,
  darkAccent: string,
  radius: ThemeDefinition['radius'] = 'rounded',
  backgroundOpacity = 0.15,
): BuiltinTheme {
  return {
    definition: {
      id,
      name,
      description,
      category,
      decoration,
      radius,
      backgroundOpacity,
      version: '1.0.0',
      light: tintedPalette(hue, lightAccent, false),
      dark: tintedPalette(hue, darkAccent, true),
    },
    imageUrl: `/themes/${id}.png`,
  };
}
export const expandedThemes: BuiltinTheme[] = [
  landscape(
    'ocean-breeze',
    '海风来信',
    '清透海蓝、柔软浪纹，把海边的呼吸带进日常。',
    'nature',
    'waves',
    '#53b6cc',
    '#28758b',
    '#8cd3e2',
    'rounded',
    0.16,
  ),
  landscape(
    'sunset-coast',
    '落日海岸',
    '杏橙色晚霞与暖沙色面板，收好一天的余温。',
    'nature',
    'sun',
    '#df956b',
    '#a75637',
    '#f3b695',
    'rounded',
    0.14,
  ),
  landscape(
    'snow-peaks',
    '雪山晨光',
    '冰川蓝、清晰轮廓与细小雪晶，像山间清晨一样明净。',
    'nature',
    'snow',
    '#92b3cd',
    '#476880',
    '#b4d1e5',
    'soft',
    0.11,
  ),
  landscape(
    'autumn-courtyard',
    '枫叶庭院',
    '枫红与暖木色相遇，在一方安静庭院里慢慢整理。',
    'ghibli',
    'leaves',
    '#c08047',
    '#945b2c',
    '#e9bc80',
    'rounded',
    0.15,
  ),
  landscape(
    'neon-city',
    '霓虹都市',
    '青紫霓虹点亮都市夜色，利落的边框和按钮保持清晰。',
    'city',
    'neon',
    '#8767bb',
    '#85539e',
    '#d5acf1',
    'square',
    0.13,
  ),
  landscape(
    'violet-cyber',
    '紫电夜航',
    '冷紫电光与几何线条，开启一段未来感的夜间航行。',
    'fantasy',
    'neon',
    '#6c65d8',
    '#654f9f',
    '#bcaafa',
    'square',
    0.12,
  ),
  landscape(
    'cosmic-nebula',
    '星河漫游',
    '钴蓝星云、柔和轨道与明亮文字，让思绪轻盈远行。',
    'fantasy',
    'orbit',
    '#657acb',
    '#4b60a1',
    '#afc1ff',
    'soft',
    0.15,
  ),
  landscape(
    'moon-desert',
    '月下沙海',
    '月牙与金色沙纹，温暖的留白包围每一条记录。',
    'fantasy',
    'moon',
    '#b49b72',
    '#876730',
    '#e2c995',
    'soft',
    0.14,
  ),
  landscape(
    'lavender-field',
    '薰衣草田',
    '浅紫花田与奶白面板，给专注的片刻一点清香。',
    'nature',
    'petals',
    '#ad8dc5',
    '#79539b',
    '#d4b7ed',
    'rounded',
    0.16,
  ),
  landscape(
    'rainy-library',
    '雨夜书房',
    '雨窗蓝绿与温润书页，在安静书房里记清每一步。',
    'city',
    'books',
    '#6599a6',
    '#3e6d7b',
    '#a1d0dc',
    'soft',
    0.13,
  ),
  landscape(
    'lotus-pond',
    '荷塘月色',
    '青荷、月白与轻柔花瓣，把东方水色铺进界面。',
    'guoman',
    'lotus',
    '#87a984',
    '#4e7049',
    '#bbd7a2',
    'rounded',
    0.14,
  ),
  landscape(
    'winter-town',
    '冬日小镇',
    '雪蓝街巷与暖灯小屋，陪你度过踏实而温柔的一天。',
    'ghibli',
    'snow',
    '#91b4c7',
    '#4b7187',
    '#aed8eb',
    'rounded',
    0.12,
  ),
];
